name: Release

on:
  push:
    branches: ['main']
    paths:
      - '.changeset/**'
      - 'CHANGELOG.md'
  pull_request:
    branches: ['main']
    paths:
      - '.changeset/**'
      - 'CHANGELOG.md'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
  coverage:
    uses: ./.github/workflows/coverage.yml

  release:
    needs: [checks, coverage]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Build Environment
        uses: ./.github/actions/ci-setup

      - name: Check for changesets
        run: pnpm changeset status --since=main

      - name: Build
        run: pnpm run build

      - name: Validate Bundle
        uses: ./.github/actions/validate-bundle

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
